### PR TITLE
refactor: use {gh} in lieu of {httr2} for calling the REST API

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by mpadge** [comment]
This is brilliant, thank! So much junk removed! Any idea what's wrong with the tests now?

**Comment by maelle** [comment]
but also why doesn't R CMD check fail?!

**Comment by mpadge** [comment]
> but also why doesn't R CMD check fail?!

Aha, it was the httptest2 redactor!  Swapping for gh changed the API path, so the old REST-path redactor was no longer applied. Fixed now

**Comment by mpadge** [comment]
Thanks to you for the PR!

**Pull request merged**
